### ISSUE TITLE
文件找不到错误

### ISSUE THREAD

**Issue by 219liangyi** [TencentTeg2018mini/TextAuidt#3]
你好。运行中发现一些路径下的文件找不到，方便提供一些简单demo吗？
文件路径：
malicious_data_url = './data/minitrill/malicious_text.txt'
normal_data_url = './data/minitrill/normal_text.txt'
./data/tf_idf.dat

**Comment by siweimei** [comment]
同问，该怎样构建这几个文件，让程序跑起来呢？

**Comment by ArlanCooper** [comment]
同问，SENSITIVE_WORDS_DATA_PATH = "./data/SensitiveWords/"  # 敏感词数据文件(要求一类数据一个txt文件)，敏感词汇表并不存在

**Comment by h-j-13** [comment]
这里自己可以构造一些数据集，之前demo的数据暂时无法提供
malicious_data_url、normal_data_url 这两个文件的格式是 
```
类型-语句
1-我爱你
1-我困了
2-操你妈
2-fuck you
```
SENSITIVE_WORDS_DATA_PATH 这里是一个敏感词文件路径，里面可以包含很多个敏感词文件
命名规则是 `类型.txt` 一个文本文件存储同一个类型的敏感词

文件格式是
```
敏感词1
敏感词2
```
