### ISSUE TITLE
文本分类语料库（复旦）测试语料  在哪找呀

### ISSUE THREAD

**Issue by ArlanCooper** [TencentTeg2018mini/TextAuidt#4]
文本分类语料库（复旦）测试语料  ，我点击了这个链接，出来的页面怎么找到相应的数据集呀

**Comment by h-j-13** [comment]
官网
![image](https://user-images.githubusercontent.com/20575663/79101726-be0ac080-7d9b-11ea-8dd3-462c7d20709d.png)
http://www.nlpir.org/wordpress/2017/10/02/%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB%E8%AF%AD%E6%96%99%E5%BA%93%EF%BC%88%E5%A4%8D%E6%97%A6%EF%BC%89%E6%B5%8B%E8%AF%95%E8%AF%AD%E6%96%99/

csdn
https://download.csdn.net/download/weixin_44210339/10902090

**Comment by ArlanCooper** [comment]
> 官网
> ![image](https://user-images.githubusercontent.com/20575663/79101726-be0ac080-7d9b-11ea-8dd3-462c7d20709d.png)
> http://www.nlpir.org/wordpress/2017/10/02/%E6%96%87%E6%9C%AC%E5%88%86%E7%B1%BB%E8%AF%AD%E6%96%99%E5%BA%93%EF%BC%88%E5%A4%8D%E6%97%A6%EF%BC%89%E6%B5%8B%E8%AF%95%E8%AF%AD%E6%96%99/
> 
> csdn
> https://download.csdn.net/download/weixin_44210339/10902090

谢谢，非常感谢
